services:
  postgres:
    container_name: postgresDB
    image: postgres:14.22-trixie
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my,s3cR3t,p4ssWORD
      POSTGRES_DB: TaskManager
    networks:
      - net-taskmanager
    ports:
      - 5432:5432
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d TaskManager"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  taskmanager:
    container_name: task-manager
    build: 
      context: ../
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgresDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my,s3cR3t,p4ssWORD
      POSTGRES_PORT: 5432
      POSTGRES_DB: TaskManager
      POSTGRES_DB_TABLE: Notes
      LOG_LEVEL: info
    ports:
      - 8080:8000
    networks:
      - net-taskmanager
    volumes:
      - postgres_db:/var/lib/postgresql/data
    
volumes:
  postgres_db:

networks:
  net-taskmanager: