services:
  postgres:
    container_name: postgresDB
    image: postgres:15-alpine
    restart: unless-stopped
    secrets:
      - postgress_user
      - postgress_password
    environment:
      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password
      POSTGRES_DB: TaskManager
    networks:
      - net-taskmanager
    ports:
      - 5432:5432
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d TaskManager"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  taskmanager:
    container_name: task-manager
    build: 
      context: ../
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    secrets:
      - postgress_user
      - postgress_password
      - postgres_host
    environment:
      # POSTGRES_HOST: postgresDB
      POSTGRES_HOST: /run/secrets/postgres_host
      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password
      POSTGRES_PORT: 5432
      POSTGRES_DB: TaskManager
      POSTGRES_DB_TABLE: Notes
      LOG_LEVEL: info
    ports:
      - 8080:8000
    networks:
      - net-taskmanager
    volumes:
      - postgres_db:/var/lib/postgresql/data
    
volumes:
  postgres_db:

networks:
  net-taskmanager:

secrets:
  postgress_user:
    file: ./env/postgres_user
  postgress_password:
    file: ./env/postgres_password
  postgres_host:
    file: ./env/postgres_host