name: Test server connection

on:
  workflow_dispatch:
   
jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: show docker images
        uses: JimCronqvist/action-ssh@1.0.0
        with:
          hosts: ${{ secrets.TFM_SERVER_USER }}@${{ secrets.TFM_SERVER_HOST }}
          privateKey: ${{ secrets.TFM_SERVER_PKEY }}
          debug: true
          command: docker images
  
          